"""empty message

Revision ID: 18169efb8854
Revises: 15a8c12a44b7
Create Date: 2019-07-10 16:13:33.182358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18169efb8854'
down_revision = '15a8c12a44b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_rate', sa.Column('iso_code_from', sa.String(length=3), nullable=False))
    op.add_column('currency_rate', sa.Column('iso_code_to', sa.String(length=3), nullable=False))
    op.drop_column('currency_rate', 'iso_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_rate', sa.Column('iso_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_column('currency_rate', 'iso_code_to')
    op.drop_column('currency_rate', 'iso_code_from')
    # ### end Alembic commands ###
